## 01. Import Library

In [1]:
#import libraries 
import pandas as pd 
import numpy as np 
import os 
import matplotlib.pyplot as plt
import seaborn as sns
import scipy

## 02. Import Path & Data Set

In [2]:
# folder shortcut path 
path = r'C:\Users\mgril\OneDrive\Desktop\UFC project folder'

In [3]:
path

'C:\\Users\\mgril\\OneDrive\\Desktop\\UFC project folder'

In [4]:
# import UFC data set
df_UFC = pd.read_csv(r'C:\Users\mgril\OneDrive\Desktop\UFC project folder\Original data UFC\UFC_csv.csv', index_col = False)

In [5]:
df_UFC = pd.read_csv(os.path.join(path, 'Original data UFC', 'UFC_csv.csv'), index_col = False)

## 03. Data Wrangling & Cleaning

In [7]:
# checking the first 5 rows and all of the columns in the imported data set
df_UFC.head()

,R_fighter,B_fighter,date,location,Winner,weight_class,B_wins,B_losses,B_draw,B_win_by_Decision_Majority,...,R_win_by_Decision_Unanimous,R_win_by_KO/TKO,R_win_by_Submission,R_win_by_TKO_Doctor_Stoppage,R_Stance,R_Height_cms,R_Reach_cms,R_Weight_lbs,B_age,R_age
0,Adrian Yanez,Gustavo Lopez,3/20/2021,"Las Vegas, Nevada, USA",Red,Bantamweight,1,1,0,0,...,0,1,0,0,Orthodox,170.18,177.80,135.0,31.0,27.0
1,Trevin Giles,Roman Dolidze,3/20/2021,"Las Vegas, Nevada, USA",Red,Middleweight,2,0,0,0,...,0,3,0,0,Orthodox,182.88,187.96,185.0,32.0,28.0
2,Tai Tuivasa,Harry Hunsucker,3/20/2021,"Las Vegas, Nevada, USA",Red,Heavyweight,0,0,0,0,...,1,3,0,0,Southpaw,187.96,190.50,264.0,32.0,28.0
3,Cheyanne Buys,Montserrat Conejo,3/20/2021,"Las Vegas, Nevada, USA",Blue,WomenStrawweight,0,0,0,0,...,0,0,0,0,Switch,160.02,160.02,115.0,28.0,25.0
4,Marion Reneau,Macy Chiasson,3/20/2021,"Las Vegas, Nevada, USA",Blue,WomenBantamweight,4,1,0,0,...,1,2,2,0,Orthodox,167.64,172.72,135.0,29.0,43.0

In [8]:
# checking total amount of rows and columns
df_UFC.shape

(6012, 34)

In [9]:
#changing column names to keep consistent format
df_UFC.rename(columns = {'R_fighter':'r_fighter','B_fighter':'b_fighter','date':'date_of_fight','Winner':'winner','B_wins':'b_wins','B_losses':'b_losses','B_draw':'b_draw','B_win_by_Decision_Majority':'b_win_by_decision_majority','B_win_by_Decision_Split':'b_win_by_decision_split','B_win_by_Decision_Unanimous':'b_win_by_decision_unanimous','B_win_by_KO/TKO':'b_win_by_ko/tko','B_win_by_Submission':'b_win_by_submission','B_win_by_TKO_Doctor_Stoppage':'b_win_by_tko_doctor_stoppage','B_Stance':'b_stance','B_Height_cms':'b_height_cms','B_Reach_cms':'b_Reach_cms','B_Weight_lbs':'b_weight_lbs','R_wins':'r_wins','R_losses':'r_losses','R_draw':'r_draw','R_win_by_Decision_Majority':'r_win_by_decision_majority','R_win_by_Decision_Split':'r_win_by_decision_split','R_win_by_Decision_Unanimous':'r_win_by_decision_unanimous','R_win_by_KO/TKO':'r_win_by_ko/tko','R_win_by_Submission':'r_win_by_submission','R_win_by_TKO_Doctor_Stoppage':'r_win_by_tko_doctor_stoppage','R_Stance':'r_stance','R_Height_cms':'r_height_cms','R_Reach_cms':'r_Reach_cms','R_Weight_lbs':'r_weight_lbs','B_age':'b_age','R_age':'r_age'}, inplace = True)

In [10]:
#checking changes applied
df_UFC.head()

,r_fighter,b_fighter,date_of_fight,location,winner,weight_class,b_wins,b_losses,b_draw,b_win_by_decision_majority,...,r_win_by_decision_unanimous,r_win_by_ko/tko,r_win_by_submission,r_win_by_tko_doctor_stoppage,r_stance,r_height_cms,r_Reach_cms,r_weight_lbs,b_age,r_age
0,Adrian Yanez,Gustavo Lopez,3/20/2021,"Las Vegas, Nevada, USA",Red,Bantamweight,1,1,0,0,...,0,1,0,0,Orthodox,170.18,177.80,135.0,31.0,27.0
1,Trevin Giles,Roman Dolidze,3/20/2021,"Las Vegas, Nevada, USA",Red,Middleweight,2,0,0,0,...,0,3,0,0,Orthodox,182.88,187.96,185.0,32.0,28.0
2,Tai Tuivasa,Harry Hunsucker,3/20/2021,"Las Vegas, Nevada, USA",Red,Heavyweight,0,0,0,0,...,1,3,0,0,Southpaw,187.96,190.50,264.0,32.0,28.0
3,Cheyanne Buys,Montserrat Conejo,3/20/2021,"Las Vegas, Nevada, USA",Blue,WomenStrawweight,0,0,0,0,...,0,0,0,0,Switch,160.02,160.02,115.0,28.0,25.0
4,Marion Reneau,Macy Chiasson,3/20/2021,"Las Vegas, Nevada, USA",Blue,WomenBantamweight,4,1,0,0,...,1,2,2,0,Orthodox,167.64,172.72,135.0,29.0,43.0

In [11]:
# descriptive statistics of the dataset
df_UFC.describe()

,b_wins,b_losses,b_draw,b_win_by_decision_majority,b_win_by_decision_split,b_win_by_decision_unanimous,b_win_by_ko/tko,b_win_by_submission,b_win_by_tko_doctor_stoppage,b_height_cms,...,r_win_by_decision_split,r_win_by_decision_unanimous,r_win_by_ko/tko,r_win_by_submission,r_win_by_tko_doctor_stoppage,r_height_cms,r_Reach_cms,r_weight_lbs,b_age,r_age
count,6012.000000,6012.000000,6012.0,6012.000000,6012.000000,6012.000000,6012.000000,6012.000000,6012.000000,6002.000000,...,6012.000000,6012.000000,6012.000000,6012.000000,6012.000000,6008.000000,5606.000000,6010.000000,5840.000000,5949.000000
mean,2.584997,1.540419,0.0,0.016134,0.218397,0.838157,0.895709,0.569528,0.042083,178.951083,...,0.306886,1.251331,1.297572,0.796241,0.069195,178.991788,183.562347,170.686356,29.293151,29.598252
std,3.317241,1.940694,0.0,0.127316,0.525232,1.370454,1.580829,1.161257,0.211290,8.709866,...,0.619485,1.681376,1.859955,1.355801,0.273980,8.812985,10.585313,35.724626,4.063297,4.167755
min,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,152.400000,...,0.000000,0.000000,0.000000,0.000000,0.000000,152.400000,152.400000,115.000000,18.000000,19.000000
25%,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,172.720000,...,0.000000,0.000000,0.000000,0.000000,0.000000,172.720000,177.800000,145.000000,26.000000,27.000000
50%,1.000000,1.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,180.340000,...,0.000000,1.000000,1.000000,0.000000,0.000000,180.340000,182.880000,170.000000,29.000000,29.000000
75%,4.000000,2.000000,0.0,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,185.420000,...,0.000000,2.000000,2.000000,1.000000,0.000000,185.420000,190.500000,185.000000,32.000000,32.000000
max,23.000000,16.000000,0.0,2.000000,5.000000,10.000000,11.000000,14.000000,2.000000,210.820000,...,5.000000,10.000000,11.000000,13.000000,2.000000,210.820000,213.360000,345.000000,51.000000,47.000000

In [12]:
# review of above dropping uneccessary columns draw. UFC has no draws. Only wins or losses. 
df_UFC = df_UFC.drop(columns= ['b_draw','r_draw'])

In [13]:
# confirm columns dropped. columns should change from 26 to 24
df_UFC.describe()

,b_wins,b_losses,b_win_by_decision_majority,b_win_by_decision_split,b_win_by_decision_unanimous,b_win_by_ko/tko,b_win_by_submission,b_win_by_tko_doctor_stoppage,b_height_cms,b_Reach_cms,...,r_win_by_decision_split,r_win_by_decision_unanimous,r_win_by_ko/tko,r_win_by_submission,r_win_by_tko_doctor_stoppage,r_height_cms,r_Reach_cms,r_weight_lbs,b_age,r_age
count,6012.000000,6012.000000,6012.000000,6012.000000,6012.000000,6012.000000,6012.000000,6012.000000,6002.000000,5121.000000,...,6012.000000,6012.000000,6012.000000,6012.000000,6012.000000,6008.000000,5606.000000,6010.000000,5840.000000,5949.000000
mean,2.584997,1.540419,0.016134,0.218397,0.838157,0.895709,0.569528,0.042083,178.951083,183.228686,...,0.306886,1.251331,1.297572,0.796241,0.069195,178.991788,183.562347,170.686356,29.293151,29.598252
std,3.317241,1.940694,0.127316,0.525232,1.370454,1.580829,1.161257,0.211290,8.709866,10.344758,...,0.619485,1.681376,1.859955,1.355801,0.273980,8.812985,10.585313,35.724626,4.063297,4.167755
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,152.400000,147.320000,...,0.000000,0.000000,0.000000,0.000000,0.000000,152.400000,152.400000,115.000000,18.000000,19.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,172.720000,177.800000,...,0.000000,0.000000,0.000000,0.000000,0.000000,172.720000,177.800000,145.000000,26.000000,27.000000
50%,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,180.340000,182.880000,...,0.000000,1.000000,1.000000,0.000000,0.000000,180.340000,182.880000,170.000000,29.000000,29.000000
75%,4.000000,2.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,185.420000,190.500000,...,0.000000,2.000000,2.000000,1.000000,0.000000,185.420000,190.500000,185.000000,32.000000,32.000000
max,23.000000,16.000000,2.000000,5.000000,10.000000,11.000000,14.000000,2.000000,210.820000,213.360000,...,5.000000,10.000000,11.000000,13.000000,2.000000,210.820000,213.360000,345.000000,51.000000,47.000000

In [14]:
#check if there is mixed data types 
for col in df_UFC.columns.tolist():
  weird = (df_UFC[[col]].applymap(type) != df_UFC[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_UFC[weird]) > 0:
    print (col)

b_stance
r_stance

In [15]:
#change the datatype of the b_stance column 
df_UFC['b_stance'] = df_UFC['b_stance'].astype(str)

In [16]:
#change the datatype of the b_stance column 
df_UFC['r_stance'] = df_UFC['r_stance'].astype(str)

In [17]:
#recheck for mixed data types
for col in df_UFC.columns.tolist():
  weird = (df_UFC[[col]].applymap(type) != df_UFC[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_UFC[weird]) > 0:
    print (col)

In [18]:
#describe the datatypes
df_UFC.dtypes

r_fighter                        object
b_fighter                        object
date_of_fight                    object
location                         object
winner                           object
weight_class                     object
b_wins                            int64
b_losses                          int64
b_win_by_decision_majority        int64
b_win_by_decision_split           int64
b_win_by_decision_unanimous       int64
b_win_by_ko/tko                   int64
b_win_by_submission               int64
b_win_by_tko_doctor_stoppage      int64
b_stance                         object
b_height_cms                    float64
b_Reach_cms                     float64
b_weight_lbs                    float64
r_wins                            int64
r_losses                          int64
r_win_by_decision_majority        int64
r_win_by_decision_split           int64
r_win_by_decision_unanimous       int64
r_win_by_ko/tko                   int64
r_win_by_submission               int64
r_win_by_tko_doctor_stoppage      int64
r_stance                         object
r_height_cms                    float64
r_Reach_cms                     float64
r_weight_lbs                    float64
b_age                           float64
r_age                           float64
dtype: object

In [19]:
#find any missing values 
df_UFC.isnull().sum()

r_fighter                         0
b_fighter                         0
date_of_fight                     0
location                          0
winner                            0
weight_class                      0
b_wins                            0
b_losses                          0
b_win_by_decision_majority        0
b_win_by_decision_split           0
b_win_by_decision_unanimous       0
b_win_by_ko/tko                   0
b_win_by_submission               0
b_win_by_tko_doctor_stoppage      0
b_stance                          0
b_height_cms                     10
b_Reach_cms                     891
b_weight_lbs                      8
r_wins                            0
r_losses                          0
r_win_by_decision_majority        0
r_win_by_decision_split           0
r_win_by_decision_unanimous       0
r_win_by_ko/tko                   0
r_win_by_submission               0
r_win_by_tko_doctor_stoppage      0
r_stance                          0
r_height_cms                      4
r_Reach_cms                     406
r_weight_lbs                      2
b_age                           172
r_age                            63
dtype: int64

In [20]:
#drop missing values in the the b_height_cms, b_Reach_cms, b_weight_lbs, r_height_cms, r_Reach_cms, r_weight_lbs, b_age,r_age    column 
df_UFC.dropna(inplace = True)

In [21]:
#check missing values again
df_UFC.isnull().sum()

r_fighter                       0
b_fighter                       0
date_of_fight                   0
location                        0
winner                          0
weight_class                    0
b_wins                          0
b_losses                        0
b_win_by_decision_majority      0
b_win_by_decision_split         0
b_win_by_decision_unanimous     0
b_win_by_ko/tko                 0
b_win_by_submission             0
b_win_by_tko_doctor_stoppage    0
b_stance                        0
b_height_cms                    0
b_Reach_cms                     0
b_weight_lbs                    0
r_wins                          0
r_losses                        0
r_win_by_decision_majority      0
r_win_by_decision_split         0
r_win_by_decision_unanimous     0
r_win_by_ko/tko                 0
r_win_by_submission             0
r_win_by_tko_doctor_stoppage    0
r_stance                        0
r_height_cms                    0
r_Reach_cms                     0
r_weight_lbs                    0
b_age                           0
r_age                           0
dtype: int64

In [22]:
#check for any duplicates 
df_dups = df_UFC[df_UFC.duplicated()]
df_dups.head(20)

Empty DataFrame
Columns: [r_fighter, b_fighter, date_of_fight, location, winner, weight_class, b_wins, b_losses, b_win_by_decision_majority, b_win_by_decision_split, b_win_by_decision_unanimous, b_win_by_ko/tko, b_win_by_submission, b_win_by_tko_doctor_stoppage, b_stance, b_height_cms, b_Reach_cms, b_weight_lbs, r_wins, r_losses, r_win_by_decision_majority, r_win_by_decision_split, r_win_by_decision_unanimous, r_win_by_ko/tko, r_win_by_submission, r_win_by_tko_doctor_stoppage, r_stance, r_height_cms, r_Reach_cms, r_weight_lbs, b_age, r_age]
Index: []

[0 rows x 32 columns]

In [23]:
#check data set before exporting 
df_UFC.shape

(4954, 32)

In [24]:
df_UFC_clean = df_UFC.drop_duplicates()

In [25]:
df_UFC_clean.shape

(4954, 32)

In [27]:
# saving and exporting cleaned data set
df_UFC_clean.to_csv(os.path.join(path, 'Prepared data UFC', 'UFC_csv.csv'))